# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 1011)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1071, 101))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 100, 991, 881))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 961, 251))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 281, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tempFreq = QtWidgets.QLabel(self.groupBox_2)
        self.tempFreq.setGeometry(QtCore.QRect(110, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.tempFreq.setFont(font)
        self.tempFreq.setText("")
        self.tempFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempFreq.setObjectName("tempFreq")
        self.freqStep1 = QtWidgets.QLabel(self.groupBox_2)
        self.freqStep1.setGeometry(QtCore.QRect(230, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.freqStep1.setFont(font)
        self.freqStep1.setObjectName("freqStep1")
        self.temp = QtWidgets.QLabel(self.groupBox_2)
        self.temp.setGeometry(QtCore.QRect(100, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.temp.setFont(font)
        self.temp.setText("")
        self.temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp.setObjectName("temp")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(250, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(250, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 20, 371, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotDataViewVerticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotDataViewVerticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.plotDataViewVerticalLayout_3.setObjectName("plotDataViewVerticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(700, 20, 251, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(10, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.readTime1 = QtWidgets.QLabel(self.groupBox_4)
        self.readTime1.setGeometry(QtCore.QRect(90, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.readTime1.setFont(font)
        self.readTime1.setText("")
        self.readTime1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.readTime1.setObjectName("readTime1")
        self.responseTime1 = QtWidgets.QLabel(self.groupBox_4)
        self.responseTime1.setGeometry(QtCore.QRect(90, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.responseTime1.setFont(font)
        self.responseTime1.setText("")
        self.responseTime1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.responseTime1.setObjectName("responseTime1")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(190, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.responseVec1 = QtWidgets.QLabel(self.groupBox_4)
        self.responseVec1.setGeometry(QtCore.QRect(90, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.responseVec1.setFont(font)
        self.responseVec1.setText("")
        self.responseVec1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.responseVec1.setObjectName("responseVec1")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(190, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 270, 961, 251))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 281, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(10, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.deformFreq = QtWidgets.QLabel(self.groupBox_6)
        self.deformFreq.setGeometry(QtCore.QRect(110, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.deformFreq.setFont(font)
        self.deformFreq.setText("")
        self.deformFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deformFreq.setObjectName("deformFreq")
        self.freqStep2 = QtWidgets.QLabel(self.groupBox_6)
        self.freqStep2.setGeometry(QtCore.QRect(220, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.freqStep2.setFont(font)
        self.freqStep2.setObjectName("freqStep2")
        self.deform = QtWidgets.QLabel(self.groupBox_6)
        self.deform.setGeometry(QtCore.QRect(100, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.deform.setFont(font)
        self.deform.setText("")
        self.deform.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deform.setObjectName("deform")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(240, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(240, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(310, 20, 371, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 351, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plotDataViewVerticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plotDataViewVerticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.plotDataViewVerticalLayout_4.setObjectName("plotDataViewVerticalLayout_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setGeometry(QtCore.QRect(700, 20, 251, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        self.label_28.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setGeometry(QtCore.QRect(10, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.readTime2 = QtWidgets.QLabel(self.groupBox_8)
        self.readTime2.setGeometry(QtCore.QRect(90, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.readTime2.setFont(font)
        self.readTime2.setText("")
        self.readTime2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.readTime2.setObjectName("readTime2")
        self.responseTime2 = QtWidgets.QLabel(self.groupBox_8)
        self.responseTime2.setGeometry(QtCore.QRect(90, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.responseTime2.setFont(font)
        self.responseTime2.setText("")
        self.responseTime2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.responseTime2.setObjectName("responseTime2")
        self.label_33 = QtWidgets.QLabel(self.groupBox_8)
        self.label_33.setGeometry(QtCore.QRect(190, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.responseVec2 = QtWidgets.QLabel(self.groupBox_8)
        self.responseVec2.setGeometry(QtCore.QRect(90, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.responseVec2.setFont(font)
        self.responseVec2.setText("")
        self.responseVec2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.responseVec2.setObjectName("responseVec2")
        self.label_35 = QtWidgets.QLabel(self.groupBox_8)
        self.label_35.setGeometry(QtCore.QRect(190, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 530, 961, 251))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 20, 281, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_36 = QtWidgets.QLabel(self.groupBox_10)
        self.label_36.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_10)
        self.label_37.setGeometry(QtCore.QRect(10, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_10)
        self.label_38.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.pressFreq = QtWidgets.QLabel(self.groupBox_10)
        self.pressFreq.setGeometry(QtCore.QRect(110, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pressFreq.setFont(font)
        self.pressFreq.setText("")
        self.pressFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pressFreq.setObjectName("pressFreq")
        self.freqStep3 = QtWidgets.QLabel(self.groupBox_10)
        self.freqStep3.setGeometry(QtCore.QRect(220, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.freqStep3.setFont(font)
        self.freqStep3.setObjectName("freqStep3")
        self.press = QtWidgets.QLabel(self.groupBox_10)
        self.press.setGeometry(QtCore.QRect(100, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.press.setFont(font)
        self.press.setText("")
        self.press.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.press.setObjectName("press")
        self.label_42 = QtWidgets.QLabel(self.groupBox_10)
        self.label_42.setGeometry(QtCore.QRect(240, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_10)
        self.label_43.setGeometry(QtCore.QRect(240, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_11.setGeometry(QtCore.QRect(310, 20, 371, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_11)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 351, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.plotDataViewVerticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.plotDataViewVerticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.plotDataViewVerticalLayout_5.setObjectName("plotDataViewVerticalLayout_5")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_12.setGeometry(QtCore.QRect(700, 20, 251, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_44 = QtWidgets.QLabel(self.groupBox_12)
        self.label_44.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_12)
        self.label_45.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_12)
        self.label_46.setGeometry(QtCore.QRect(10, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.readTime3 = QtWidgets.QLabel(self.groupBox_12)
        self.readTime3.setGeometry(QtCore.QRect(90, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.readTime3.setFont(font)
        self.readTime3.setText("")
        self.readTime3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.readTime3.setObjectName("readTime3")
        self.responseTime3 = QtWidgets.QLabel(self.groupBox_12)
        self.responseTime3.setGeometry(QtCore.QRect(90, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.responseTime3.setFont(font)
        self.responseTime3.setText("")
        self.responseTime3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.responseTime3.setObjectName("responseTime3")
        self.label_50 = QtWidgets.QLabel(self.groupBox_12)
        self.label_50.setGeometry(QtCore.QRect(190, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.responseVec3 = QtWidgets.QLabel(self.groupBox_12)
        self.responseVec3.setGeometry(QtCore.QRect(90, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.responseVec3.setFont(font)
        self.responseVec3.setText("")
        self.responseVec3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.responseVec3.setObjectName("responseVec3")
        self.label_52 = QtWidgets.QLabel(self.groupBox_12)
        self.label_52.setGeometry(QtCore.QRect(190, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_22.setGeometry(QtCore.QRect(130, 790, 651, 61))
        self.groupBox_22.setObjectName("groupBox_22")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_22)
        self.comboBox.setGeometry(QtCore.QRect(80, 20, 221, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.testButton = QtWidgets.QPushButton(self.groupBox_22)
        self.testButton.setGeometry(QtCore.QRect(350, 20, 221, 31))
        self.testButton.setObjectName("testButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.formGroupBox = QtWidgets.QGroupBox(self.tab2)
        self.formGroupBox.setGeometry(QtCore.QRect(20, 10, 271, 361))
        self.formGroupBox.setObjectName("formGroupBox")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setGeometry(QtCore.QRect(11, 30, 101, 31))
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.checkComButton = QtWidgets.QPushButton(self.formGroupBox)
        self.checkComButton.setGeometry(QtCore.QRect(110, 30, 151, 31))
        self.checkComButton.setAutoRepeatInterval(100)
        self.checkComButton.setDefault(True)
        self.checkComButton.setObjectName("checkComButton")
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setGeometry(QtCore.QRect(11, 70, 101, 31))
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.selectComButton = QtWidgets.QComboBox(self.formGroupBox)
        self.selectComButton.setGeometry(QtCore.QRect(110, 70, 151, 31))
        self.selectComButton.setObjectName("selectComButton")
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_3.setGeometry(QtCore.QRect(11, 120, 101, 31))
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.baudrate = QtWidgets.QComboBox(self.formGroupBox)
        self.baudrate.setGeometry(QtCore.QRect(110, 120, 151, 31))
        self.baudrate.setObjectName("baudrate")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_4.setGeometry(QtCore.QRect(11, 160, 101, 31))
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.databit = QtWidgets.QComboBox(self.formGroupBox)
        self.databit.setGeometry(QtCore.QRect(110, 160, 151, 31))
        self.databit.setObjectName("databit")
        self.databit.addItem("")
        self.databit.addItem("")
        self.databit.addItem("")
        self.databit.addItem("")
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_5.setGeometry(QtCore.QRect(11, 200, 111, 31))
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.checkbit = QtWidgets.QComboBox(self.formGroupBox)
        self.checkbit.setGeometry(QtCore.QRect(110, 200, 151, 31))
        self.checkbit.setObjectName("checkbit")
        self.checkbit.addItem("")
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_6.setGeometry(QtCore.QRect(11, 240, 91, 31))
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.stopbit = QtWidgets.QComboBox(self.formGroupBox)
        self.stopbit.setGeometry(QtCore.QRect(110, 240, 151, 31))
        self.stopbit.setObjectName("stopbit")
        self.stopbit.addItem("")
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setGeometry(QtCore.QRect(10, 280, 251, 31))
        self.open_button.setObjectName("open_button")
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setGeometry(QtCore.QRect(10, 320, 251, 31))
        self.close_button.setObjectName("close_button")
        self.formGroupBox_2 = QtWidgets.QGroupBox(self.tab2)
        self.formGroupBox_2.setGeometry(QtCore.QRect(20, 450, 271, 91))
        self.formGroupBox_2.setObjectName("formGroupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox_2)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_53 = QtWidgets.QLabel(self.formGroupBox_2)
        self.label_53.setObjectName("label_53")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.label_54 = QtWidgets.QLabel(self.formGroupBox_2)
        self.label_54.setObjectName("label_54")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.recieveComData = QtWidgets.QLineEdit(self.formGroupBox_2)
        self.recieveComData.setObjectName("recieveComData")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recieveComData)
        self.sendComData = QtWidgets.QLineEdit(self.formGroupBox_2)
        self.sendComData.setObjectName("sendComData")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sendComData)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_13.setGeometry(QtCore.QRect(330, 10, 631, 281))
        self.groupBox_13.setObjectName("groupBox_13")
        self.one_stage_T = QtWidgets.QTextEdit(self.groupBox_13)
        self.one_stage_T.setGeometry(QtCore.QRect(110, 50, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one_stage_T.sizePolicy().hasHeightForWidth())
        self.one_stage_T.setSizePolicy(sizePolicy)
        self.one_stage_T.setPlaceholderText("")
        self.one_stage_T.setObjectName("one_stage_T")
        self.two_stage_T = QtWidgets.QTextEdit(self.groupBox_13)
        self.two_stage_T.setGeometry(QtCore.QRect(110, 110, 151, 41))
        self.two_stage_T.setPlaceholderText("")
        self.two_stage_T.setObjectName("two_stage_T")
        self.zero_stage_T = QtWidgets.QTextEdit(self.groupBox_13)
        self.zero_stage_T.setGeometry(QtCore.QRect(110, 170, 151, 41))
        self.zero_stage_T.setPlaceholderText("")
        self.zero_stage_T.setObjectName("zero_stage_T")
        self.send_para = QtWidgets.QPushButton(self.groupBox_13)
        self.send_para.setGeometry(QtCore.QRect(280, 230, 151, 31))
        self.send_para.setObjectName("send_para")
        self.label_55 = QtWidgets.QLabel(self.groupBox_13)
        self.label_55.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_13)
        self.label_56.setGeometry(QtCore.QRect(10, 120, 91, 21))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_13)
        self.label_57.setGeometry(QtCore.QRect(10, 180, 91, 21))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_13)
        self.label_58.setGeometry(QtCore.QRect(150, 24, 72, 21))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.groupBox_13)
        self.label_59.setGeometry(QtCore.QRect(330, 26, 72, 20))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_13)
        self.label_60.setGeometry(QtCore.QRect(510, 24, 72, 21))
        self.label_60.setObjectName("label_60")
        self.one_stage_D = QtWidgets.QTextEdit(self.groupBox_13)
        self.one_stage_D.setGeometry(QtCore.QRect(280, 50, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one_stage_D.sizePolicy().hasHeightForWidth())
        self.one_stage_D.setSizePolicy(sizePolicy)
        self.one_stage_D.setPlaceholderText("")
        self.one_stage_D.setObjectName("one_stage_D")
        self.two_stage_D = QtWidgets.QTextEdit(self.groupBox_13)
        self.two_stage_D.setGeometry(QtCore.QRect(280, 110, 151, 41))
        self.two_stage_D.setPlaceholderText("")
        self.two_stage_D.setObjectName("two_stage_D")
        self.zero_stage_D = QtWidgets.QTextEdit(self.groupBox_13)
        self.zero_stage_D.setGeometry(QtCore.QRect(280, 170, 151, 41))
        self.zero_stage_D.setPlaceholderText("")
        self.zero_stage_D.setObjectName("zero_stage_D")
        self.one_stage_P = QtWidgets.QTextEdit(self.groupBox_13)
        self.one_stage_P.setGeometry(QtCore.QRect(450, 50, 151, 41))
        self.one_stage_P.setPlaceholderText("")
        self.one_stage_P.setObjectName("one_stage_P")
        self.two_stage_P = QtWidgets.QTextEdit(self.groupBox_13)
        self.two_stage_P.setGeometry(QtCore.QRect(450, 110, 151, 41))
        self.two_stage_P.setPlaceholderText("")
        self.two_stage_P.setObjectName("two_stage_P")
        self.zero_stage_P = QtWidgets.QTextEdit(self.groupBox_13)
        self.zero_stage_P.setGeometry(QtCore.QRect(450, 170, 151, 41))
        self.zero_stage_P.setPlaceholderText("")
        self.zero_stage_P.setObjectName("zero_stage_P")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab2)
        self.tabWidget_2.setGeometry(QtCore.QRect(680, 320, 271, 321))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 251, 281))
        self.groupBox_14.setObjectName("groupBox_14")
        self.textEditStartFreq = QtWidgets.QTextEdit(self.groupBox_14)
        self.textEditStartFreq.setGeometry(QtCore.QRect(20, 30, 111, 41))
        self.textEditStartFreq.setObjectName("textEditStartFreq")
        self.sendFreqButton = QtWidgets.QPushButton(self.groupBox_14)
        self.sendFreqButton.setGeometry(QtCore.QRect(70, 240, 111, 31))
        self.sendFreqButton.setObjectName("sendFreqButton")
        self.textEditEndFreq = QtWidgets.QTextEdit(self.groupBox_14)
        self.textEditEndFreq.setGeometry(QtCore.QRect(20, 80, 111, 41))
        self.textEditEndFreq.setObjectName("textEditEndFreq")
        self.rssiThreshold = QtWidgets.QTextEdit(self.groupBox_14)
        self.rssiThreshold.setGeometry(QtCore.QRect(20, 130, 111, 41))
        self.rssiThreshold.setObjectName("rssiThreshold")
        self.rssiThresholdSpan = QtWidgets.QTextEdit(self.groupBox_14)
        self.rssiThresholdSpan.setGeometry(QtCore.QRect(20, 180, 111, 41))
        self.rssiThresholdSpan.setObjectName("rssiThresholdSpan")
        self.label_61 = QtWidgets.QLabel(self.groupBox_14)
        self.label_61.setGeometry(QtCore.QRect(160, 35, 91, 21))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_14)
        self.label_62.setGeometry(QtCore.QRect(160, 90, 91, 21))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_14)
        self.label_63.setGeometry(QtCore.QRect(160, 140, 91, 21))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_14)
        self.label_64.setGeometry(QtCore.QRect(160, 190, 91, 21))
        self.label_64.setObjectName("label_64")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 10, 251, 281))
        self.groupBox_15.setObjectName("groupBox_15")
        self.textEditStartFreq_2 = QtWidgets.QTextEdit(self.groupBox_15)
        self.textEditStartFreq_2.setGeometry(QtCore.QRect(20, 30, 111, 41))
        self.textEditStartFreq_2.setObjectName("textEditStartFreq_2")
        self.sendFreqButton_2 = QtWidgets.QPushButton(self.groupBox_15)
        self.sendFreqButton_2.setGeometry(QtCore.QRect(70, 240, 111, 31))
        self.sendFreqButton_2.setObjectName("sendFreqButton_2")
        self.textEditEndFreq_2 = QtWidgets.QTextEdit(self.groupBox_15)
        self.textEditEndFreq_2.setGeometry(QtCore.QRect(20, 80, 111, 41))
        self.textEditEndFreq_2.setObjectName("textEditEndFreq_2")
        self.rssiThreshold_2 = QtWidgets.QTextEdit(self.groupBox_15)
        self.rssiThreshold_2.setGeometry(QtCore.QRect(20, 130, 111, 41))
        self.rssiThreshold_2.setObjectName("rssiThreshold_2")
        self.rssiThresholdSpan_2 = QtWidgets.QTextEdit(self.groupBox_15)
        self.rssiThresholdSpan_2.setGeometry(QtCore.QRect(20, 180, 111, 41))
        self.rssiThresholdSpan_2.setObjectName("rssiThresholdSpan_2")
        self.label_65 = QtWidgets.QLabel(self.groupBox_15)
        self.label_65.setGeometry(QtCore.QRect(160, 35, 81, 21))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_15)
        self.label_66.setGeometry(QtCore.QRect(160, 90, 81, 21))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_15)
        self.label_67.setGeometry(QtCore.QRect(160, 140, 68, 21))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_15)
        self.label_68.setGeometry(QtCore.QRect(160, 190, 71, 21))
        self.label_68.setObjectName("label_68")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 10, 251, 281))
        self.groupBox_16.setObjectName("groupBox_16")
        self.textEditStartFreq_3 = QtWidgets.QTextEdit(self.groupBox_16)
        self.textEditStartFreq_3.setGeometry(QtCore.QRect(20, 30, 111, 41))
        self.textEditStartFreq_3.setObjectName("textEditStartFreq_3")
        self.sendFreqButton_3 = QtWidgets.QPushButton(self.groupBox_16)
        self.sendFreqButton_3.setGeometry(QtCore.QRect(70, 240, 111, 31))
        self.sendFreqButton_3.setObjectName("sendFreqButton_3")
        self.textEditEndFreq_3 = QtWidgets.QTextEdit(self.groupBox_16)
        self.textEditEndFreq_3.setGeometry(QtCore.QRect(20, 80, 111, 41))
        self.textEditEndFreq_3.setObjectName("textEditEndFreq_3")
        self.rssiThreshold_3 = QtWidgets.QTextEdit(self.groupBox_16)
        self.rssiThreshold_3.setGeometry(QtCore.QRect(20, 130, 111, 41))
        self.rssiThreshold_3.setObjectName("rssiThreshold_3")
        self.rssiThresholdSpan_3 = QtWidgets.QTextEdit(self.groupBox_16)
        self.rssiThresholdSpan_3.setGeometry(QtCore.QRect(20, 180, 111, 41))
        self.rssiThresholdSpan_3.setObjectName("rssiThresholdSpan_3")
        self.label_69 = QtWidgets.QLabel(self.groupBox_16)
        self.label_69.setGeometry(QtCore.QRect(160, 35, 81, 21))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_16)
        self.label_70.setGeometry(QtCore.QRect(160, 90, 81, 21))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupBox_16)
        self.label_71.setGeometry(QtCore.QRect(160, 140, 68, 21))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_16)
        self.label_72.setGeometry(QtCore.QRect(160, 190, 71, 21))
        self.label_72.setObjectName("label_72")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_17.setGeometry(QtCore.QRect(330, 310, 311, 141))
        self.groupBox_17.setObjectName("groupBox_17")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_17)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 201, 41))
        self.checkBox.setObjectName("checkBox")
        self.freqChange = QtWidgets.QTextEdit(self.groupBox_17)
        self.freqChange.setGeometry(QtCore.QRect(110, 60, 91, 31))
        self.freqChange.setObjectName("freqChange")
        self.sendFreqRangeButton = QtWidgets.QPushButton(self.groupBox_17)
        self.sendFreqRangeButton.setGeometry(QtCore.QRect(110, 100, 91, 31))
        self.sendFreqRangeButton.setAutoFillBackground(False)
        self.sendFreqRangeButton.setAutoDefault(False)
        self.sendFreqRangeButton.setObjectName("sendFreqRangeButton")
        self.label_73 = QtWidgets.QLabel(self.groupBox_17)
        self.label_73.setGeometry(QtCore.QRect(220, 60, 61, 31))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_17)
        self.label_74.setGeometry(QtCore.QRect(50, 60, 61, 31))
        self.label_74.setObjectName("label_74")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_18.setGeometry(QtCore.QRect(330, 510, 311, 131))
        self.groupBox_18.setObjectName("groupBox_18")
        self.save2FileRealTime = QtWidgets.QCheckBox(self.groupBox_18)
        self.save2FileRealTime.setGeometry(QtCore.QRect(20, 10, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.save2FileRealTime.setFont(font)
        self.save2FileRealTime.setObjectName("save2FileRealTime")
        self.selectFileButton = QtWidgets.QPushButton(self.groupBox_18)
        self.selectFileButton.setGeometry(QtCore.QRect(100, 80, 121, 31))
        self.selectFileButton.setObjectName("selectFileButton")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_19.setGeometry(QtCore.QRect(20, 580, 271, 251))
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.groupBox_19)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(10, 20, 251, 81))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.send_text = QtWidgets.QTextEdit(self.verticalGroupBox_2)
        self.send_text.setPlaceholderText("")
        self.send_text.setObjectName("send_text")
        self.verticalLayout_2.addWidget(self.send_text)
        self.timer_send_cb = QtWidgets.QCheckBox(self.groupBox_19)
        self.timer_send_cb.setGeometry(QtCore.QRect(10, 110, 121, 41))
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.hex_send = QtWidgets.QCheckBox(self.groupBox_19)
        self.hex_send.setGeometry(QtCore.QRect(140, 110, 121, 41))
        self.hex_send.setObjectName("hex_send")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 160, 61, 21))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.dw = QtWidgets.QLabel(self.groupBox_19)
        self.dw.setGeometry(QtCore.QRect(140, 160, 71, 20))
        self.dw.setObjectName("dw")
        self.sendTextButton = QtWidgets.QPushButton(self.groupBox_19)
        self.sendTextButton.setGeometry(QtCore.QRect(50, 200, 61, 31))
        self.sendTextButton.setObjectName("sendTextButton")
        self.timeclock_clear_button = QtWidgets.QPushButton(self.groupBox_19)
        self.timeclock_clear_button.setGeometry(QtCore.QRect(140, 200, 61, 31))
        self.timeclock_clear_button.setObjectName("timeclock_clear_button")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_21.setGeometry(QtCore.QRect(330, 710, 311, 121))
        self.groupBox_21.setObjectName("groupBox_21")
        self.receive_text = QtWidgets.QTextBrowser(self.groupBox_21)
        self.receive_text.setGeometry(QtCore.QRect(20, 20, 281, 41))
        self.receive_text.setObjectName("receive_text")
        self.hex_receive = QtWidgets.QCheckBox(self.groupBox_21)
        self.hex_receive.setGeometry(QtCore.QRect(20, 70, 121, 31))
        self.hex_receive.setChecked(False)
        self.hex_receive.setObjectName("hex_receive")
        self.clear_button = QtWidgets.QPushButton(self.groupBox_21)
        self.clear_button.setGeometry(QtCore.QRect(190, 70, 100, 32))
        self.clear_button.setObjectName("clear_button")
        self.saveTempAndFreq = QtWidgets.QPushButton(self.tab2)
        self.saveTempAndFreq.setGeometry(QtCore.QRect(680, 690, 271, 41))
        self.saveTempAndFreq.setObjectName("saveTempAndFreq")
        self.rotateBox = QtWidgets.QCheckBox(self.tab2)
        self.rotateBox.setGeometry(QtCore.QRect(770, 780, 91, 41))
        self.rotateBox.setObjectName("rotateBox")
        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "浙江大学SAW无线无源传感系统实时检测系统"))
        self.groupBox.setTitle(_translate("MainWindow", "温度"))
        self.groupBox_2.setTitle(_translate("MainWindow", "传感值"))
        self.label_3.setText(_translate("MainWindow", "当前频率值："))
        self.label_4.setText(_translate("MainWindow", "频率解析度："))
        self.label_5.setText(_translate("MainWindow", "当前温度值："))
        self.freqStep1.setText(_translate("MainWindow", "1 Hz"))
        self.label_8.setText(_translate("MainWindow", "Hz"))
        self.label_9.setText(_translate("MainWindow", "℃"))
        self.groupBox_3.setTitle(_translate("MainWindow", "温度变化曲线"))
        self.groupBox_4.setTitle(_translate("MainWindow", "响应"))
        self.label_10.setText(_translate("MainWindow", "读取时间："))
        self.label_11.setText(_translate("MainWindow", "响应时间："))
        self.label_12.setText(_translate("MainWindow", "响应速度："))
        self.label_16.setText(_translate("MainWindow", "s"))
        self.label_18.setText(_translate("MainWindow", "秒/次"))
        self.groupBox_5.setTitle(_translate("MainWindow", "应变"))
        self.groupBox_6.setTitle(_translate("MainWindow", "传感值"))
        self.label_19.setText(_translate("MainWindow", "当前频率值："))
        self.label_20.setText(_translate("MainWindow", "频率解析度："))
        self.label_21.setText(_translate("MainWindow", "当前应变值："))
        self.freqStep2.setText(_translate("MainWindow", "1 Hz"))
        self.label_25.setText(_translate("MainWindow", "Hz"))
        self.label_26.setText(_translate("MainWindow", "με"))
        self.groupBox_7.setTitle(_translate("MainWindow", "应变变化曲线"))
        self.groupBox_8.setTitle(_translate("MainWindow", "响应"))
        self.label_27.setText(_translate("MainWindow", "读取时间："))
        self.label_28.setText(_translate("MainWindow", "响应时间："))
        self.label_29.setText(_translate("MainWindow", "响应速度："))
        self.label_33.setText(_translate("MainWindow", "s"))
        self.label_35.setText(_translate("MainWindow", "秒/次"))
        self.groupBox_9.setTitle(_translate("MainWindow", "压力"))
        self.groupBox_10.setTitle(_translate("MainWindow", "传感值"))
        self.label_36.setText(_translate("MainWindow", "当前频率值："))
        self.label_37.setText(_translate("MainWindow", "频率解析度："))
        self.label_38.setText(_translate("MainWindow", "当前压力值："))
        self.freqStep3.setText(_translate("MainWindow", "1 Hz"))
        self.label_42.setText(_translate("MainWindow", "Hz"))
        self.label_43.setText(_translate("MainWindow", "MPa"))
        self.groupBox_11.setTitle(_translate("MainWindow", "压力变化曲线"))
        self.groupBox_12.setTitle(_translate("MainWindow", "响应"))
        self.label_44.setText(_translate("MainWindow", "读取时间："))
        self.label_45.setText(_translate("MainWindow", "响应时间："))
        self.label_46.setText(_translate("MainWindow", "响应速度："))
        self.label_50.setText(_translate("MainWindow", "s"))
        self.label_52.setText(_translate("MainWindow", "秒/次"))
        self.groupBox_22.setTitle(_translate("MainWindow", "工作模式"))
        self.comboBox.setItemText(0, _translate("MainWindow", "单天线工作"))
        self.comboBox.setItemText(1, _translate("MainWindow", "双天线工作"))
        self.comboBox.setItemText(2, _translate("MainWindow", "单天线功率检波"))
        self.comboBox.setItemText(3, _translate("MainWindow", "双天线功率检波"))
        self.testButton.setText(_translate("MainWindow", "开始测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "主窗口"))
        self.formGroupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.s1__lb_1.setText(_translate("MainWindow", "串口检测："))
        self.checkComButton.setText(_translate("MainWindow", "检测串口"))
        self.s1__lb_2.setText(_translate("MainWindow", "串口选择："))
        self.s1__lb_3.setText(_translate("MainWindow", "波特率："))
        self.baudrate.setItemText(0, _translate("MainWindow", "115200"))
        self.baudrate.setItemText(1, _translate("MainWindow", "2400"))
        self.baudrate.setItemText(2, _translate("MainWindow", "4800"))
        self.baudrate.setItemText(3, _translate("MainWindow", "9600"))
        self.baudrate.setItemText(4, _translate("MainWindow", "14400"))
        self.baudrate.setItemText(5, _translate("MainWindow", "19200"))
        self.baudrate.setItemText(6, _translate("MainWindow", "38400"))
        self.baudrate.setItemText(7, _translate("MainWindow", "57600"))
        self.baudrate.setItemText(8, _translate("MainWindow", "76800"))
        self.baudrate.setItemText(9, _translate("MainWindow", "12800"))
        self.baudrate.setItemText(10, _translate("MainWindow", "230400"))
        self.baudrate.setItemText(11, _translate("MainWindow", "460800"))
        self.s1__lb_4.setText(_translate("MainWindow", "数据位："))
        self.databit.setItemText(0, _translate("MainWindow", "8"))
        self.databit.setItemText(1, _translate("MainWindow", "7"))
        self.databit.setItemText(2, _translate("MainWindow", "6"))
        self.databit.setItemText(3, _translate("MainWindow", "5"))
        self.s1__lb_5.setText(_translate("MainWindow", "校验位："))
        self.checkbit.setItemText(0, _translate("MainWindow", "N"))
        self.s1__lb_6.setText(_translate("MainWindow", "停止位："))
        self.stopbit.setItemText(0, _translate("MainWindow", "1"))
        self.open_button.setText(_translate("MainWindow", "打开串口"))
        self.close_button.setText(_translate("MainWindow", "关闭串口"))
        self.formGroupBox_2.setTitle(_translate("MainWindow", "串口状态（已关闭）"))
        self.label_53.setText(_translate("MainWindow", "已接收："))
        self.label_54.setText(_translate("MainWindow", "已发送："))
        self.groupBox_13.setTitle(_translate("MainWindow", "拟合函数设置"))
        self.send_para.setText(_translate("MainWindow", "发送"))
        self.label_55.setText(_translate("MainWindow", "一次系数"))
        self.label_56.setText(_translate("MainWindow", "二次系数"))
        self.label_57.setText(_translate("MainWindow", "偏置"))
        self.label_58.setText(_translate("MainWindow", "温度"))
        self.label_59.setText(_translate("MainWindow", "微应变"))
        self.label_60.setText(_translate("MainWindow", "压力"))
        self.groupBox_14.setTitle(_translate("MainWindow", "频率和阈值设置"))
        self.textEditStartFreq.setPlaceholderText(_translate("MainWindow", "开始频率"))
        self.sendFreqButton.setText(_translate("MainWindow", "发送"))
        self.textEditEndFreq.setPlaceholderText(_translate("MainWindow", "结束频率"))
        self.rssiThreshold.setPlaceholderText(_translate("MainWindow", "阈值"))
        self.rssiThresholdSpan.setPlaceholderText(_translate("MainWindow", "阈值范围"))
        self.label_61.setText(_translate("MainWindow", "开始频率"))
        self.label_62.setText(_translate("MainWindow", "结束频率"))
        self.label_63.setText(_translate("MainWindow", "阈值"))
        self.label_64.setText(_translate("MainWindow", "阈值范围"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "温度"))
        self.groupBox_15.setTitle(_translate("MainWindow", "频率和阈值设置"))
        self.textEditStartFreq_2.setPlaceholderText(_translate("MainWindow", "开始频率"))
        self.sendFreqButton_2.setText(_translate("MainWindow", "发送"))
        self.textEditEndFreq_2.setPlaceholderText(_translate("MainWindow", "结束频率"))
        self.rssiThreshold_2.setPlaceholderText(_translate("MainWindow", "阈值"))
        self.rssiThresholdSpan_2.setPlaceholderText(_translate("MainWindow", "阈值范围"))
        self.label_65.setText(_translate("MainWindow", "开始频率"))
        self.label_66.setText(_translate("MainWindow", "结束频率"))
        self.label_67.setText(_translate("MainWindow", "阈值"))
        self.label_68.setText(_translate("MainWindow", "阈值范围"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "应变"))
        self.groupBox_16.setTitle(_translate("MainWindow", "频率和阈值设置"))
        self.textEditStartFreq_3.setPlaceholderText(_translate("MainWindow", "开始频率"))
        self.sendFreqButton_3.setText(_translate("MainWindow", "发送"))
        self.textEditEndFreq_3.setPlaceholderText(_translate("MainWindow", "结束频率"))
        self.rssiThreshold_3.setPlaceholderText(_translate("MainWindow", "阈值"))
        self.rssiThresholdSpan_3.setPlaceholderText(_translate("MainWindow", "阈值范围"))
        self.label_69.setText(_translate("MainWindow", "开始频率"))
        self.label_70.setText(_translate("MainWindow", "结束频率"))
        self.label_71.setText(_translate("MainWindow", "阈值"))
        self.label_72.setText(_translate("MainWindow", "阈值范围"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "压力"))
        self.groupBox_17.setTitle(_translate("MainWindow", "扫频频率变化"))
        self.checkBox.setText(_translate("MainWindow", "跟随谐振频率变化"))
        self.freqChange.setPlaceholderText(_translate("MainWindow", "频率范围"))
        self.sendFreqRangeButton.setText(_translate("MainWindow", "发送"))
        self.label_73.setText(_translate("MainWindow", "MHz"))
        self.label_74.setText(_translate("MainWindow", "Span:"))
        self.groupBox_18.setTitle(_translate("MainWindow", "实时保存文件"))
        self.save2FileRealTime.setText(_translate("MainWindow", "实时保存数据为文件"))
        self.selectFileButton.setText(_translate("MainWindow", "选择文件"))
        self.groupBox_19.setTitle(_translate("MainWindow", "发送区"))
        self.verticalGroupBox_2.setTitle(_translate("MainWindow", "发送内容"))
        self.send_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">123456</p></body></html>"))
        self.timer_send_cb.setText(_translate("MainWindow", "定时发送"))
        self.hex_send.setText(_translate("MainWindow", "Hex发送"))
        self.lineEdit_3.setText(_translate("MainWindow", "1,000"))
        self.dw.setText(_translate("MainWindow", "ms/次"))
        self.sendTextButton.setText(_translate("MainWindow", "发送"))
        self.timeclock_clear_button.setText(_translate("MainWindow", "清除"))
        self.groupBox_21.setTitle(_translate("MainWindow", "接收区"))
        self.hex_receive.setText(_translate("MainWindow", "Hex接收"))
        self.clear_button.setText(_translate("MainWindow", "清除"))
        self.saveTempAndFreq.setText(_translate("MainWindow", "保存温度和谐振频率"))
        self.rotateBox.setText(_translate("MainWindow", "旋转"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "设置"))

