# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1454, 890)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setGeometry(QtCore.QRect(30, 80, 241, 311))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_3)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.s1__lb_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.s1__box_4)
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_5)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_5)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.s1__lb_6)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.s1__box_6)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.open_button)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.close_button)
        self.formGroupBox1 = QtWidgets.QGroupBox(Form)
        self.formGroupBox1.setGeometry(QtCore.QRect(30, 430, 241, 101))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox1)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formGroupBox1)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setEnabled(True)
        self.logo.setGeometry(QtCore.QRect(30, 0, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setAutoFillBackground(False)
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo.setText("")
        self.logo.setTextFormat(QtCore.Qt.PlainText)
        self.logo.setPixmap(QtGui.QPixmap("logo_60.png"))
        self.logo.setScaledContents(False)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setIndent(-2)
        self.logo.setObjectName("logo")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(120, 10, 911, 61))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.RichText)
        self.title.setObjectName("title")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(840, 700, 211, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.receiveText_2 = QtWidgets.QTextBrowser(self.groupBox_2)
        self.receiveText_2.setGeometry(QtCore.QRect(10, 30, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveText_2.sizePolicy().hasHeightForWidth())
        self.receiveText_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.receiveText_2.setFont(font)
        self.receiveText_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.receiveText_2.setObjectName("receiveText_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(170, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(1080, 650, 281, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.checkBox.setObjectName("checkBox")
        self.freqChange = QtWidgets.QTextEdit(self.groupBox_4)
        self.freqChange.setGeometry(QtCore.QRect(80, 60, 91, 31))
        self.freqChange.setObjectName("freqChange")
        self.sendFreqRangeButton = QtWidgets.QPushButton(self.groupBox_4)
        self.sendFreqRangeButton.setGeometry(QtCore.QRect(90, 100, 91, 31))
        self.sendFreqRangeButton.setAutoFillBackground(False)
        self.sendFreqRangeButton.setAutoDefault(False)
        self.sendFreqRangeButton.setObjectName("sendFreqRangeButton")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(190, 60, 51, 31))
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(30, 60, 41, 31))
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1050, 820, 311, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.saveTempAndFreq = QtWidgets.QPushButton(Form)
        self.saveTempAndFreq.setGeometry(QtCore.QRect(310, 800, 181, 51))
        self.saveTempAndFreq.setObjectName("saveTempAndFreq")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 580, 241, 271))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(10, 30, 181, 81))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.s3__send_text = QtWidgets.QTextEdit(self.verticalGroupBox_2)
        self.s3__send_text.setPlaceholderText("")
        self.s3__send_text.setObjectName("s3__send_text")
        self.verticalLayout_2.addWidget(self.s3__send_text)
        self.timer_send_cb = QtWidgets.QCheckBox(self.groupBox_7)
        self.timer_send_cb.setGeometry(QtCore.QRect(10, 130, 101, 16))
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.hex_send = QtWidgets.QCheckBox(self.groupBox_7)
        self.hex_send.setGeometry(QtCore.QRect(120, 130, 101, 16))
        self.hex_send.setObjectName("hex_send")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 170, 61, 20))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.dw = QtWidgets.QLabel(self.groupBox_7)
        self.dw.setGeometry(QtCore.QRect(120, 170, 54, 20))
        self.dw.setObjectName("dw")
        self.s3__send_button = QtWidgets.QPushButton(self.groupBox_7)
        self.s3__send_button.setGeometry(QtCore.QRect(30, 210, 61, 31))
        self.s3__send_button.setObjectName("s3__send_button")
        self.s3__clear_button = QtWidgets.QPushButton(self.groupBox_7)
        self.s3__clear_button.setGeometry(QtCore.QRect(130, 210, 61, 31))
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(640, 790, 411, 61))
        self.groupBox_8.setObjectName("groupBox_8")
        self.save2FileRealTime = QtWidgets.QCheckBox(self.groupBox_8)
        self.save2FileRealTime.setGeometry(QtCore.QRect(180, -10, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.save2FileRealTime.setFont(font)
        self.save2FileRealTime.setObjectName("save2FileRealTime")
        self.selectFileButton = QtWidgets.QPushButton(self.groupBox_8)
        self.selectFileButton.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.selectFileButton.setObjectName("selectFileButton")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(1080, 80, 281, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 251, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEditStartFreq = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEditStartFreq.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.textEditStartFreq.setObjectName("textEditStartFreq")
        self.sendFreqButton = QtWidgets.QPushButton(self.groupBox_3)
        self.sendFreqButton.setGeometry(QtCore.QRect(70, 190, 111, 31))
        self.sendFreqButton.setObjectName("sendFreqButton")
        self.textEditEndFreq = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEditEndFreq.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.textEditEndFreq.setObjectName("textEditEndFreq")
        self.textEditEndFreq_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEditEndFreq_2.setGeometry(QtCore.QRect(20, 110, 111, 31))
        self.textEditEndFreq_2.setObjectName("textEditEndFreq_2")
        self.rssiThreshold_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.rssiThreshold_2.setGeometry(QtCore.QRect(20, 150, 111, 31))
        self.rssiThreshold_2.setObjectName("rssiThreshold_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(160, 40, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(160, 80, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(160, 120, 68, 15))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(160, 160, 71, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 20, 251, 231))
        self.groupBox_12.setObjectName("groupBox_12")
        self.textEditStartFreq_2 = QtWidgets.QTextEdit(self.groupBox_12)
        self.textEditStartFreq_2.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.textEditStartFreq_2.setObjectName("textEditStartFreq_2")
        self.sendFreqButton_2 = QtWidgets.QPushButton(self.groupBox_12)
        self.sendFreqButton_2.setGeometry(QtCore.QRect(70, 190, 111, 31))
        self.sendFreqButton_2.setObjectName("sendFreqButton_2")
        self.textEditEndFreq_3 = QtWidgets.QTextEdit(self.groupBox_12)
        self.textEditEndFreq_3.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.textEditEndFreq_3.setObjectName("textEditEndFreq_3")
        self.textEditEndFreq_4 = QtWidgets.QTextEdit(self.groupBox_12)
        self.textEditEndFreq_4.setGeometry(QtCore.QRect(20, 110, 111, 31))
        self.textEditEndFreq_4.setObjectName("textEditEndFreq_4")
        self.rssiThreshold_3 = QtWidgets.QTextEdit(self.groupBox_12)
        self.rssiThreshold_3.setGeometry(QtCore.QRect(20, 150, 111, 31))
        self.rssiThreshold_3.setObjectName("rssiThreshold_3")
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        self.label_20.setGeometry(QtCore.QRect(160, 40, 81, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_12)
        self.label_21.setGeometry(QtCore.QRect(160, 80, 81, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setGeometry(QtCore.QRect(160, 120, 68, 15))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setGeometry(QtCore.QRect(160, 160, 71, 16))
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 20, 251, 231))
        self.groupBox_14.setObjectName("groupBox_14")
        self.textEditStartFreq_3 = QtWidgets.QTextEdit(self.groupBox_14)
        self.textEditStartFreq_3.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.textEditStartFreq_3.setObjectName("textEditStartFreq_3")
        self.sendFreqButton_3 = QtWidgets.QPushButton(self.groupBox_14)
        self.sendFreqButton_3.setGeometry(QtCore.QRect(70, 190, 111, 31))
        self.sendFreqButton_3.setObjectName("sendFreqButton_3")
        self.textEditEndFreq_5 = QtWidgets.QTextEdit(self.groupBox_14)
        self.textEditEndFreq_5.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.textEditEndFreq_5.setObjectName("textEditEndFreq_5")
        self.textEditEndFreq_6 = QtWidgets.QTextEdit(self.groupBox_14)
        self.textEditEndFreq_6.setGeometry(QtCore.QRect(20, 110, 111, 31))
        self.textEditEndFreq_6.setObjectName("textEditEndFreq_6")
        self.rssiThreshold_4 = QtWidgets.QTextEdit(self.groupBox_14)
        self.rssiThreshold_4.setGeometry(QtCore.QRect(20, 150, 111, 31))
        self.rssiThreshold_4.setObjectName("rssiThreshold_4")
        self.label_24 = QtWidgets.QLabel(self.groupBox_14)
        self.label_24.setGeometry(QtCore.QRect(160, 40, 81, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_14)
        self.label_25.setGeometry(QtCore.QRect(160, 80, 81, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_14)
        self.label_26.setGeometry(QtCore.QRect(160, 120, 68, 15))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_14)
        self.label_27.setGeometry(QtCore.QRect(160, 160, 71, 16))
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox_16 = QtWidgets.QGroupBox(Form)
        self.groupBox_16.setGeometry(QtCore.QRect(310, 80, 741, 601))
        self.groupBox_16.setObjectName("groupBox_16")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(170, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.receiveText = QtWidgets.QTextBrowser(self.groupBox)
        self.receiveText.setGeometry(QtCore.QRect(10, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.receiveText.setFont(font)
        self.receiveText.setReadOnly(True)
        self.receiveText.setMarkdown("")
        self.receiveText.setObjectName("receiveText")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_9.setGeometry(QtCore.QRect(250, 20, 231, 71))
        self.groupBox_9.setObjectName("groupBox_9")
        self.receive_deform = QtWidgets.QTextBrowser(self.groupBox_9)
        self.receive_deform.setGeometry(QtCore.QRect(10, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.receive_deform.setFont(font)
        self.receive_deform.setReadOnly(True)
        self.receive_deform.setMarkdown("")
        self.receive_deform.setObjectName("receive_deform")
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setGeometry(QtCore.QRect(150, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_10.setGeometry(QtCore.QRect(490, 20, 231, 71))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        self.label_14.setGeometry(QtCore.QRect(160, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.receiveText_5 = QtWidgets.QTextBrowser(self.groupBox_10)
        self.receiveText_5.setGeometry(QtCore.QRect(10, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.receiveText_5.setFont(font)
        self.receiveText_5.setReadOnly(True)
        self.receiveText_5.setMarkdown("")
        self.receiveText_5.setObjectName("receiveText_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_16)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 711, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotDataViewVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotDataViewVerticalLayout.setContentsMargins(0, 0, 4, 0)
        self.plotDataViewVerticalLayout.setObjectName("plotDataViewVerticalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 490, 711, 81))
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QtCore.QRect(40, 30, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.testButton = QtWidgets.QPushButton(self.groupBox_6)
        self.testButton.setGeometry(QtCore.QRect(540, 30, 141, 31))
        self.testButton.setObjectName("testButton")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 30, 171, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.groupBox_11 = QtWidgets.QGroupBox(Form)
        self.groupBox_11.setGeometry(QtCore.QRect(1080, 410, 281, 211))
        self.groupBox_11.setObjectName("groupBox_11")
        self.one_stage_T = QtWidgets.QTextEdit(self.groupBox_11)
        self.one_stage_T.setGeometry(QtCore.QRect(80, 40, 51, 31))
        self.one_stage_T.setPlaceholderText("")
        self.one_stage_T.setObjectName("one_stage_T")
        self.two_stage_T = QtWidgets.QTextEdit(self.groupBox_11)
        self.two_stage_T.setGeometry(QtCore.QRect(80, 90, 51, 31))
        self.two_stage_T.setPlaceholderText("")
        self.two_stage_T.setObjectName("two_stage_T")
        self.zero_stage_T = QtWidgets.QTextEdit(self.groupBox_11)
        self.zero_stage_T.setGeometry(QtCore.QRect(80, 140, 51, 31))
        self.zero_stage_T.setPlaceholderText("")
        self.zero_stage_T.setObjectName("zero_stage_T")
        self.send_para = QtWidgets.QPushButton(self.groupBox_11)
        self.send_para.setGeometry(QtCore.QRect(130, 180, 41, 31))
        self.send_para.setObjectName("send_para")
        self.label_12 = QtWidgets.QLabel(self.groupBox_11)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 72, 15))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        self.label_15.setGeometry(QtCore.QRect(10, 100, 72, 15))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setGeometry(QtCore.QRect(20, 150, 72, 15))
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        self.label_19.setGeometry(QtCore.QRect(80, 20, 72, 15))
        self.label_19.setObjectName("label_19")
        self.label_18 = QtWidgets.QLabel(self.groupBox_11)
        self.label_18.setGeometry(QtCore.QRect(140, 20, 72, 16))
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox_11)
        self.label_17.setGeometry(QtCore.QRect(210, 20, 72, 15))
        self.label_17.setObjectName("label_17")
        self.one_stage_D = QtWidgets.QTextEdit(self.groupBox_11)
        self.one_stage_D.setGeometry(QtCore.QRect(140, 40, 51, 31))
        self.one_stage_D.setPlaceholderText("")
        self.one_stage_D.setObjectName("one_stage_D")
        self.two_stage_D = QtWidgets.QTextEdit(self.groupBox_11)
        self.two_stage_D.setGeometry(QtCore.QRect(140, 90, 51, 31))
        self.two_stage_D.setPlaceholderText("")
        self.two_stage_D.setObjectName("two_stage_D")
        self.zero_stage_D = QtWidgets.QTextEdit(self.groupBox_11)
        self.zero_stage_D.setGeometry(QtCore.QRect(140, 140, 51, 31))
        self.zero_stage_D.setPlaceholderText("")
        self.zero_stage_D.setObjectName("zero_stage_D")
        self.one_stage_P = QtWidgets.QTextEdit(self.groupBox_11)
        self.one_stage_P.setGeometry(QtCore.QRect(200, 40, 51, 31))
        self.one_stage_P.setPlaceholderText("")
        self.one_stage_P.setObjectName("one_stage_P")
        self.two_stage_P = QtWidgets.QTextEdit(self.groupBox_11)
        self.two_stage_P.setGeometry(QtCore.QRect(200, 90, 51, 31))
        self.two_stage_P.setPlaceholderText("")
        self.two_stage_P.setObjectName("two_stage_P")
        self.zero_stage_P = QtWidgets.QTextEdit(self.groupBox_11)
        self.zero_stage_P.setGeometry(QtCore.QRect(200, 140, 51, 31))
        self.zero_stage_P.setPlaceholderText("")
        self.zero_stage_P.setObjectName("zero_stage_P")
        self.verticalGroupBox = QtWidgets.QGroupBox(Form)
        self.verticalGroupBox.setGeometry(QtCore.QRect(310, 700, 461, 81))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.horizontalLayout.addWidget(self.s2__receive_text)
        self.hex_receive = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.hex_receive.setObjectName("hex_receive")
        self.horizontalLayout.addWidget(self.hex_receive)
        self.s2__clear_button = QtWidgets.QPushButton(self.verticalGroupBox)
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.horizontalLayout.addWidget(self.s2__clear_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_16.raise_()
        self.groupBox_7.raise_()
        self.formGroupBox.raise_()
        self.formGroupBox.raise_()
        self.logo.raise_()
        self.title.raise_()
        self.groupBox_2.raise_()
        self.groupBox_4.raise_()
        self.label_5.raise_()
        self.saveTempAndFreq.raise_()
        self.groupBox_8.raise_()
        self.tabWidget.raise_()
        self.groupBox_11.raise_()
        self.verticalGroupBox.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.formGroupBox.setTitle(_translate("Form", "串口设置"))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.s1__lb_3.setText(_translate("Form", "波特率："))
        self.s1__box_3.setItemText(0, _translate("Form", "115200"))
        self.s1__box_3.setItemText(1, _translate("Form", "2400"))
        self.s1__box_3.setItemText(2, _translate("Form", "4800"))
        self.s1__box_3.setItemText(3, _translate("Form", "9600"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "230400"))
        self.s1__box_3.setItemText(11, _translate("Form", "460800"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.formGroupBox1.setTitle(_translate("Form", "串口状态（已关闭）"))
        self.label.setText(_translate("Form", "已接收："))
        self.label_2.setText(_translate("Form", "已发送："))
        self.title.setText(_translate("Form", "SAW无线无源多参数传感系统"))
        self.groupBox_2.setTitle(_translate("Form", "响应时间"))
        self.receiveText_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("Form", "s"))
        self.groupBox_4.setTitle(_translate("Form", "扫频频率变化"))
        self.checkBox.setText(_translate("Form", "跟随谐振频率变化"))
        self.freqChange.setPlaceholderText(_translate("Form", "频率范围"))
        self.sendFreqRangeButton.setText(_translate("Form", "发送"))
        self.label_6.setText(_translate("Form", "MHz"))
        self.label_11.setText(_translate("Form", "Span:"))
        self.label_5.setText(_translate("Form", "Powered by ZJU, 2022"))
        self.saveTempAndFreq.setText(_translate("Form", "保存温度和谐振频率"))
        self.groupBox_7.setTitle(_translate("Form", "发送区"))
        self.verticalGroupBox_2.setTitle(_translate("Form", "发送内容"))
        self.s3__send_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">123456</p></body></html>"))
        self.timer_send_cb.setText(_translate("Form", "定时发送"))
        self.hex_send.setText(_translate("Form", "Hex发送"))
        self.lineEdit_3.setText(_translate("Form", "1,000"))
        self.dw.setText(_translate("Form", "ms/次"))
        self.s3__send_button.setText(_translate("Form", "发送"))
        self.s3__clear_button.setText(_translate("Form", "清除"))
        self.groupBox_8.setTitle(_translate("Form", "实时保存文件"))
        self.save2FileRealTime.setText(_translate("Form", "实时保存数据为文件"))
        self.selectFileButton.setText(_translate("Form", "选择文件"))
        self.groupBox_3.setTitle(_translate("Form", "频率和阈值设置"))
        self.textEditStartFreq.setPlaceholderText(_translate("Form", "开始频率"))
        self.sendFreqButton.setText(_translate("Form", "发送"))
        self.textEditEndFreq.setPlaceholderText(_translate("Form", "结束频率"))
        self.textEditEndFreq_2.setPlaceholderText(_translate("Form", "阈值"))
        self.rssiThreshold_2.setPlaceholderText(_translate("Form", "阈值范围"))
        self.label_7.setText(_translate("Form", "开始频率"))
        self.label_8.setText(_translate("Form", "结束频率"))
        self.label_9.setText(_translate("Form", "阈值"))
        self.label_10.setText(_translate("Form", "阈值范围"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "温度"))
        self.groupBox_12.setTitle(_translate("Form", "频率和阈值设置"))
        self.textEditStartFreq_2.setPlaceholderText(_translate("Form", "开始频率"))
        self.sendFreqButton_2.setText(_translate("Form", "发送"))
        self.textEditEndFreq_3.setPlaceholderText(_translate("Form", "结束频率"))
        self.textEditEndFreq_4.setPlaceholderText(_translate("Form", "阈值"))
        self.rssiThreshold_3.setPlaceholderText(_translate("Form", "阈值范围"))
        self.label_20.setText(_translate("Form", "开始频率"))
        self.label_21.setText(_translate("Form", "结束频率"))
        self.label_22.setText(_translate("Form", "阈值"))
        self.label_23.setText(_translate("Form", "阈值范围"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "应变"))
        self.groupBox_14.setTitle(_translate("Form", "频率和阈值设置"))
        self.textEditStartFreq_3.setPlaceholderText(_translate("Form", "开始频率"))
        self.sendFreqButton_3.setText(_translate("Form", "发送"))
        self.textEditEndFreq_5.setPlaceholderText(_translate("Form", "结束频率"))
        self.textEditEndFreq_6.setPlaceholderText(_translate("Form", "阈值"))
        self.rssiThreshold_4.setPlaceholderText(_translate("Form", "阈值范围"))
        self.label_24.setText(_translate("Form", "开始频率"))
        self.label_25.setText(_translate("Form", "结束频率"))
        self.label_26.setText(_translate("Form", "阈值"))
        self.label_27.setText(_translate("Form", "阈值范围"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "压力"))
        self.groupBox_16.setTitle(_translate("Form", "监测指标"))
        self.groupBox.setTitle(_translate("Form", "温度"))
        self.label_3.setText(_translate("Form", "℃"))
        self.receiveText.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_9.setTitle(_translate("Form", "应变"))
        self.receive_deform.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("Form", "微应变"))
        self.groupBox_10.setTitle(_translate("Form", "压力"))
        self.label_14.setText(_translate("Form", "MPa"))
        self.receiveText_5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_6.setTitle(_translate("Form", "工作模式"))
        self.comboBox.setItemText(0, _translate("Form", "单天线工作"))
        self.comboBox.setItemText(1, _translate("Form", "双天线工作"))
        self.comboBox.setItemText(2, _translate("Form", "单天线功率检波"))
        self.comboBox.setItemText(3, _translate("Form", "双天线功率检波"))
        self.testButton.setText(_translate("Form", "开始测试"))
        self.comboBox_2.setItemText(0, _translate("Form", "温度测试"))
        self.comboBox_2.setItemText(1, _translate("Form", "应变测试"))
        self.comboBox_2.setItemText(2, _translate("Form", "压力测试"))
        self.groupBox_11.setTitle(_translate("Form", "拟合函数设置"))
        self.send_para.setText(_translate("Form", "发送"))
        self.label_12.setText(_translate("Form", "一次系数"))
        self.label_15.setText(_translate("Form", "二次系数"))
        self.label_16.setText(_translate("Form", "偏置"))
        self.label_19.setText(_translate("Form", "温度"))
        self.label_18.setText(_translate("Form", "微应变"))
        self.label_17.setText(_translate("Form", "压力"))
        self.verticalGroupBox.setTitle(_translate("Form", "接收区"))
        self.hex_receive.setText(_translate("Form", "Hex接收"))
        self.s2__clear_button.setText(_translate("Form", "清除"))

